flasher: sometimes all you have is usb to sata...
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/arm64/usr/sbin/beagle-flasher-boot-mmc-rootfs-sda b/arm64/usr/sbin/beagle-flasher-boot-mmc-rootfs-sda
--- a/arm64/usr/sbin/beagle-flasher-boot-mmc-rootfs-sda
+++ b/arm64/usr/sbin/beagle-flasher-boot-mmc-rootfs-sda
@@ -1,8 +1,8 @@
 #!/bin/bash -e
 
 if ! id | grep -q root; then
-	echo "beagle-flasher-boot-emmc-rootfs-nvme must be run as root:"
-	echo "sudo beagle-flasher-boot-emmc-rootfs-nvme"
+	echo "beagle-flasher-boot-mmc-rootfs-sda must be run as root:"
+	echo "sudo beagle-flasher-boot-mmc-rootfs-sda"
 	exit
 fi
 
@@ -159,7 +159,7 @@ write_failure () {
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 	if [ "x${destination}" != "x" ] ; then
-		umount ${destination}p1 > /dev/null 2>&1 || true
+		umount ${destination}1 > /dev/null 2>&1 || true
 	fi
 }
 
@@ -240,32 +240,32 @@ check_running_system () {
 }
 
 format_boot () {
-	message="/sbin/mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}"                          ; broadcast
-	LC_ALL=C /sbin/mkfs.vfat -F 16 ${destination}p1 -n ${boot_label}
+	message="/sbin/mkfs.vfat -F 16 ${destination}1 -n ${boot_label}"                          ; broadcast
+	LC_ALL=C /sbin/mkfs.vfat -F 16 ${destination}1 -n ${boot_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
 format_root () {
-	message="/sbin/mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}"              ; broadcast
-	LC_ALL=C /sbin/mkfs.ext4 ${ext4_options} ${destination}p${dest_rfs_part} -L ${rootfs_label}
+	message="/sbin/mkfs.ext4 ${ext4_options} ${destination}${dest_rfs_part} -L ${rootfs_label}"              ; broadcast
+	LC_ALL=C /sbin/mkfs.ext4 ${ext4_options} ${destination}${dest_rfs_part} -L ${rootfs_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
 format_single_root () {
-	message="/sbin/mkfs.ext4 ${mkfs_options} ${destination}p1 -L ${single_root_label}"         ; broadcast
-	LC_ALL=C /sbin/mkfs.ext4 ${mkfs_options} ${destination}p1 -L ${single_root_label}
+	message="/sbin/mkfs.ext4 ${mkfs_options} ${destination}1 -L ${single_root_label}"         ; broadcast
+	LC_ALL=C /sbin/mkfs.ext4 ${mkfs_options} ${destination}1 -L ${single_root_label}
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 }
 
 copy_rootfs () {
-	message="INFO: Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part}"       ; broadcast
+	message="INFO: Copying: ${source}p${src_rfs_part} -> ${destination}${dest_rfs_part}"       ; broadcast
 	mkdir -p /tmp/rootfs/ || true
 
-	message="INFO: [mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime]"       ; broadcast
-	mount ${destination}p${dest_rfs_part} /tmp/rootfs/ -o async,noatime
+	message="INFO: [mount ${destination}${dest_rfs_part} /tmp/rootfs/ -o async,noatime]"       ; broadcast
+	mount ${destination}${dest_rfs_part} /tmp/rootfs/ -o async,noatime
 
 	message="INFO: /usr/bin/rsync: (-aHAXx) [/ -> /tmp/rootfs/]"                                ; broadcast
 	/usr/bin/rsync -aHAXx --human-readable --info=progress2 /* /tmp/rootfs/ --exclude={/dev/*,/proc/*,/sys/*,/tmp/*,/run/*,/mnt/*,/media/*,/lost+found,/lib/modules/*,/boot/firmware/*} || write_failure
@@ -287,7 +287,7 @@ copy_rootfs () {
 	message="INFO: Generating: /etc/fstab"                                                     ;  broadcast
 	echo "# /etc/fstab: static file system information." > /tmp/rootfs/etc/fstab
 	echo "#" >> /tmp/rootfs/etc/fstab
-	echo "${destination}p${dest_rfs_part}  /  ext4  noatime,errors=remount-ro  0  1" >> /tmp/rootfs/etc/fstab
+	echo "${destination}${dest_rfs_part}  /  ext4  noatime,errors=remount-ro  0  1" >> /tmp/rootfs/etc/fstab
 	echo "${source}p1  /boot/firmware vfat defaults 0 0" >> /tmp/rootfs/etc/fstab
 	echo "debugfs  /sys/kernel/debug  debugfs  mode=755,uid=root,gid=gpio,defaults  0  0" >> /tmp/rootfs/etc/fstab
 	message="INFO: [cat /tmp/rootfs/etc/fstab]"                                                ; broadcast
@@ -304,7 +304,7 @@ copy_rootfs () {
 	fi
 	flush_cache
 
-	message="Copying: ${source}p${src_rfs_part} -> ${destination}p${dest_rfs_part} complete"    ; broadcast
+	message="Copying: ${source}p${src_rfs_part} -> ${destination}${dest_rfs_part} complete"    ; broadcast
 	message="--------------------------------------------------------------------------------" ; broadcast
 	flush_cache
 
@@ -443,7 +443,7 @@ partition_drive () {
 		format_boot
 		format_root
 		if [ "x${rfs_swap_size_mb}" != "x" ] ; then
-			LC_ALL=C /sbin/mkswap ${destination}p2
+			LC_ALL=C /sbin/mkswap ${destination}2
 		fi
 		message="INFO: Formatting: ${destination} complete"                                        ; broadcast
 		message="--------------------------------------------------------------------------------" ; broadcast
