bb-wl18xx-select-fw: these should be under usr now
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/arm32/usr/sbin/bb-wl18xx-select-fw b/arm32/usr/sbin/bb-wl18xx-select-fw
--- a/arm32/usr/sbin/bb-wl18xx-select-fw
+++ b/arm32/usr/sbin/bb-wl18xx-select-fw
@@ -34,14 +34,18 @@ else
 	if [ -f /lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin ] ; then
 		echo "Updating /etc/default/bb-wl18xx-fw with [WLFW=wl18xx-fw-4-${FW_OPTION}.bin]"
 		echo "WLFW=wl18xx-fw-4-${FW_OPTION}.bin" > /etc/default/bb-wl18xx-fw
-		rm -rf /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
-		cp -v /lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin /lib/firmware/ti-connectivity/wl18xx-fw-4.bin
+		rm -rf /usr/lib/firmware/ti-connectivity/wl18xx-fw-4.bin
+		cp -v /usr/lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin /usr/lib/firmware/ti-connectivity/wl18xx-fw-4.bin
 		sync
 		#Some users dont run with an initrd.img
 		if [ -f /boot/initrd.img-`uname -r` ] ; then
 			update-initramfs -u || true
 		fi
+		if [ -f /boot/firmware/initrd.img ] ; then
+			update-initramfs -u || true
+			cp -v /boot/initrd.img-`uname -r` /boot/firmware/initrd.img
+		fi
 	else
-		echo "Unable to find /lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin"
+		echo "Unable to find /usr/lib/firmware/ti-connectivity/git/wl18xx-fw-4-${FW_OPTION}.bin"
 	fi
 fi
