bb-start-acm-ncm-rndis-old-gadget: rework product/manu
Signed-off-by: Robert Nelson <robertcnelson@gmail.com>

diff --git a/arm64/usr/bin/bb-start-acm-ncm-rndis-old-gadget b/arm64/usr/bin/bb-start-acm-ncm-rndis-old-gadget
--- a/arm64/usr/bin/bb-start-acm-ncm-rndis-old-gadget
+++ b/arm64/usr/bin/bb-start-acm-ncm-rndis-old-gadget
@@ -48,8 +48,8 @@ usb_ms_imagefile=/etc/bbb.io/templates/beagle-getting-started.img
 #cpsw_4_mac = usb1 (BeagleBone Side)
 #cpsw_5_mac = usb1 (USB host, pc side)
 
-deviceinfo_usb_imanufacturer="BeagleBoard.org"
-deviceinfo_usb_iproduct="$(cat /proc/device-tree/model | sed "s/ /_/g" | tr -d '\000')"
+deviceinfo_usb_imanufacturer="$(cat /proc/device-tree/model | awk '{print $1}' | tr -d '\000')"
+deviceinfo_usb_iproduct="$(cat /proc/device-tree/model | awk '{print $2}' | tr -d '\000')"
 
 if [ -f /etc/default/usb-oem ] ; then
 	. /etc/default/usb-oem
@@ -66,10 +66,8 @@ usb_idProduct="${deviceinfo_usb_idProduct:-0x0104}" # Multifunction Composite Ga
 usb_bcdDevice="${deviceinfo_usb_bcdDevice:-0x0404}"
 usb_bcdUSB="${deviceinfo_usb_bcdUSB:-0x0200}"
 
-#usb_imanufacturer="$(cat /proc/device-tree/model | awk '{print $1}' | tr -d '\000')"
 usb_imanufacturer="${deviceinfo_usb_imanufacturer:-BeagleBoard.org}"
 usb_serialnumber="${deviceinfo_usb_serialnumber:-1234BBBK5678}"
-#usb_iproduct="$(cat /proc/device-tree/model | awk '{print $2}' | tr -d '\000')"
 usb_iproduct="${deviceinfo_usb_iproduct:-BeagleBone}"
 
 
@@ -91,20 +89,18 @@ run_libcomposite () {
 		echo "$usb_iserialnumber" > "$CONFIGFS/g_multi/strings/0x409/serialnumber"
 		echo "$usb_iproduct" > "$CONFIGFS/g_multi/strings/0x409/product"
 
-		cd ${CONFIGFS}/g_multi
 		# Windows extension to use IAD (Interface Association Descriptor)
 		# https://learn.microsoft.com/en-us/windows-hardware/drivers/usbcon/usb-interface-association-descriptor
-		echo "0xEF" > bDeviceClass
-		echo "0x02" > bDeviceSubClass
-		echo "0x01" > bDeviceProtocol
-		echo "0x0100" > bcdDevice
+		echo "0xEF" > "$CONFIGFS/g_multi/bDeviceClass"
+		echo "0x02" > "$CONFIGFS/g_multi/bDeviceSubClass"
+		echo "0x01" > "$CONFIGFS/g_multi/bDeviceProtocol"
+		echo "0x0100" > "$CONFIGFS/g_multi/bcdDevice"
 
+		mkdir -p $CONFIGFS/g_multi/configs/c.1/strings/0x409 || echo "${log} Couldn't create $CONFIGFS/g_multi/configs/c.1/strings/0x409"
+		echo "BeagleBone Composite" > "$CONFIGFS/g_multi/configs/c.1/strings/0x409/configuration"
+		echo "500" > "$CONFIGFS/g_multi/configs/c.1/MaxPower"
 
-		mkdir -p configs/c.1/strings/0x409
-		echo "BeagleBone Composite" > configs/c.1/strings/0x409/configuration
-
-		echo 500 > configs/c.1/MaxPower
-
+		cd ${CONFIGFS}/g_multi
 		# Enable use of OS descriptor (for windows to bind drivers like NCM, RNDIS...
 		# without additional .inf file)
 		mkdir -p os_desc
@@ -149,7 +145,7 @@ run_libcomposite () {
 		fi
 
 		###FIXME:
-		sleep 3
+		sleep 2
 
 		# Check if there's an USB Device Controller
 		if [ -z "$(ls /sys/class/udc)" ]; then
